services:
  npm:
    image: jc21/nginx-proxy-manager:2.14.0
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./data/npm:/data
      - ./data/npm-letsencrypt:/etc/letsencrypt
    networks:
      - bill-network
    restart: unless-stopped

  app:
    image: emmitmeira/bill:1.2.2
    expose:
      - "8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/bill
      BILL_ADMIN_USERNAME: admin
      BILL_ADMIN_PASSWORD: "256301"
    depends_on:
      - mongodb
    networks:
      - bill-network
    restart: unless-stopped

  mongodb:
    image: mongo:7
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - bill-network
    restart: unless-stopped

networks:
  bill-network:
    driver: bridge
