spring.application.name=bill
spring.data.mongodb.uri=mongodb://localhost:27017/bill
spring.thymeleaf.cache=false
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**
